version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential npm nodejs
      - checkout
      - run: npm install
  deploy-bundle-analysis:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential npm nodejs
      - checkout
      - run: npm install
      - run: npm run analyze
      - run: mkdir report && cp dist/report.html report/report.html
      - run: CODE_GOV_RELATIVE_DIR='/report' CODE_GOV_BRANCH='federalist-bundle-analysis' npm publish
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy-bundle-analysis:
          requires:
            - build
          filters:
            branches:
              only: master
